application: webdaily-2016
version: 1
runtime: python27
threadsafe: false
api_version: 1
libraries:
- name: jinja2
  version: "latest"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
